name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      environment: 
        name: page
      permissions:
        contents: write
      steps:
        - name: Compact display
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.REPO_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
            plugin_achievements_display: compact
            plugin_achievements_threshold: X
        - name: Featured star list languages
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.starlists.languages.svg
            token: NOT_NEEDED
            base: ""
            plugin_starlists: yes
            plugin_starlists_languages: yes
            plugin_starlists_limit_languages: 8
            plugin_starlists_limit_repositories: 0
            plugin_starlists_only: Awesome
