name: Metrics
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      environment: 
        name: page
      permissions:
        contents: write
      steps:
        - name: Compact display
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.REPO_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
            plugin_achievements_display: compact
            plugin_achievements_threshold: X
        - name: Full history calendar
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.calendar.full.svg
            token: ${{ secrets.REPO_TOKEN }}
            base: ""
            plugin_calendar: yes
            plugin_calendar_limit: 0

